
[Python的异常处理](https://docs.python.org/3/library/exceptions.html#exception-hierarchy)

## 一、错误处理try···except···finally···

- Python的异常处理是``try···except···finally···``不是``try···catch···finally···``

- Python的异常也是class，所有的异常都继承BaseException类。

- Python异常类会捕获自身及其所有子类的异常。

- Python异常捕获可跨界多层调用。

- 如果异常没有被捕获，会一直往上抛（raise），最后被Python解释器捕获。

- logging模块可记录异常日志，也可以输出到指定文件。


```python
try:
    print('try...')
    r = 10 / 0
    print('result:', r)
except ZeroDivisionError as e:
    print('execpt:', e)
finally:
    print('finally...')
print('END')

try...
execpt: division by zero
finally...
END
```

异常跨界多层调用与捕获：

```python
def foo(s):
        return 10 / int(s) # 异常在foo()中发生
def bar(s):
        return foo(s) * 2
def main(): # 异常在main中捕获
        try:
            bar('0')
        except Exception as  e:
            print('error:', e)
        finally:
            print('finally')
```

## 二、调试

调试方法：

- print()方法打印日志

- assert断言


assert断言是条件不成立，则抛出后面的异常信息。

```python
def foo(s):
        n = int(s)
        assert n != 0, 'n is zreo'
        return 10 / n
def main():
        foo('0')
main()

```

可以在程序启动时设置所有的断言失效：

```python
python3 -O erroroperation.py
Traceback (most recent call last):
  File "erroroperation.py", line 7, in <module>
    main()
  File "erroroperation.py", line 6, in main
    foo('0')
  File "erroroperation.py", line 4, in foo
    return 10 / n
ZeroDivisionError: division by zero
```

- logging

logging允许你指定记录信息的级别，有debug，info，warning，error等几个级别，当我们指定level=INFO时，logging.debug就不起作用了。同理，指定level=WARNING后，debug和info就不起作用了。这样一来，你可以放心地输出不同级别的信息，也不用删除，最后统一控制输出哪个级别的信息。

logging的另一个好处是通过简单的配置，一条语句可以同时输出到不同的地方，比如console和文件。

```python
import  logging
logging.basicConfig(level=logging.INFO)
s = '0'
n = int(s)
logging.info('n = %d' % n)
print(10 / n)

INFO:root:n = 0
Traceback (most recent call last):
  File "/Users/erroroperation.py", line 6, in <module>
    print(10 / n)
ZeroDivisionError: division by zero
```

- pdb

Python的调试器pdb可以允许单步执行程序，可随时查看运行状态。

```python
s = '0'
n = int(s)
print(10 / n)

$ -m pdb erroroperation.py # 开启pdb调试
> /Users/erroroperation.py(1)<module>()
-> s = '0'
(Pdb) n # 单步执行
> /Users/erroroperation.py(2)<module>()
-> n = int(s)
(Pdb) p s # 查看变量
'0'
(Pdb) l # 查看代码
  1  	s = '0'
  2  ->	n = int(s)
  3  	print(10 / n)
[EOF]
(Pdb) n
> /Users/erroroperation.py(3)<module>()
-> print(10 / n)
(Pdb) n
ZeroDivisionError: division by zero
> /Users/erroroperation.py(3)<module>()
-> print(10 / n)
(Pdb) q # 退出
```

- pdb.set_trace

pdb.set_trace可让代码在指定的位置暂停并进入pdb调试环境，可以用p命令查看变量或者c命令继续执行。

```python
import pdb
s = '0'
n = int(s)
pdb.set_trace() # 运行到这里自动暂停
print(10 / n)

$ python3 erroroperation.py
> /Users/erroroperation.py(5)<module>()
-> print(10 / n)
(Pdb) p n
0
(Pdb) c
Traceback (most recent call last):
  File "erroroperation.py", line 5, in <module>
    print(10 / n)
ZeroDivisionError: division by zero

```

## 三、单元测试

## 四、文档测试



